visitor_analysis/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

visitor_analysis/visitor_analysis/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('visitors/', include('visitors.urls')),
    path('about/', views.about),
    path('', accounts_views.login_view, name = 'home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

visitor_analysis/visitors/urls.py
from django.urls import path
from . import views

app_name = 'visitors'

urlpatterns = [
    path('', views.visitors, name="list" ),
    path('register/', views.visitor_register, name="register"),
    path('<int:id>/', views.visitor_detail, name="detail"),
    path('report/', views.visitor_report, name="report"),
    path('dashboard/', views.dashboard_with_pivot, name='dashboard_with_pivot'),
    path('dashboard/data/', views.pivot_data, name='pivot_data'),
]

visitor_analysis/accounts/models.py
from django.db import models

# Create your models here.

visitor_analysis/visitors/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
AGE_CHOICE = [
    (0, "under 5"),
    (5, "5 - 9"),
    (10, "10 - 14"),
    (15, "15 - 19"),
    (20, "20 - 30"),
    (30, "30 - 40"),
    (40, "40 - 50"),
    (50, "50 - 60"),
    (60, "above 60"),
]

GENDER_CHOICES = [
    ("F", "Female"),
    ("M", "Male"),
    ]

class Visitor(models.Model):
    age = models.IntegerField(choices=AGE_CHOICE)
    gender = models.CharField(max_length = 2, choices = GENDER_CHOICES)
    date = models.DateField(auto_now_add = True)
    time = models.TimeField(auto_now_add = True)
    # thumb = models.ImageField(default = 'default.png', blank = True)
    user = models.ForeignKey(User, default = None, on_delete=models.CASCADE)

    # def __int__(self):
    #     return self.id

visitor_analysis/visitors/forms.py
from django import forms
from . import models

class RegisterVisitor(forms.ModelForm):
    class Meta:
        model = models.Visitor
        fields = ['age', 'gender'] 

visitor_analysis/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)

            return redirect('visitors:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('visitors:list')        
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('visitors:list')  

visitor_analysis/visitor_analysis/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')


def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

visitor_analysis/visitors/views.py
from django.shortcuts import render, redirect
from .models import Visitor
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from . import report
from . import analysis

from django.http import JsonResponse
from django.core import serializers
# Create your views here.

def visitors(request):
    visitors = Visitor.objects.all().order_by('date')
    return render(request, 'visitors/visitors.html', {'visitors':visitors})

def visitor_detail(request, id):
    visitor = Visitor.objects.get(id=id)
    return render(request, 'visitors/visitor_detail.html', {'visitor':visitor})

@login_required(login_url="/accounts/login/")
def visitor_register(request):
    if request.method == 'POST':
        form = forms.RegisterVisitor(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect("visitors:register")
    else:
        form = forms.RegisterVisitor()
    return render(request, 'visitors/visitor_register.html', {'form':form})

# Report
@login_required(login_url="/accounts/login/")
def visitor_report(request):
    if request.method == 'POST':
        date = request.POST.get("date")
        selected_date = Visitor.objects.filter(date=date)
        df, df_csv = report.data_to_df(selected_date) # visitor table
        visitor_num = Visitor.objects.filter(date=date).count() # total number of visitor
        gender = analysis.gender_analysis(df_csv) # gender ratio pie chart
        age = analysis.age_analysis(df_csv) # age dischart
        time = analysis.time_analysis(df_csv) # time dischart
        return render(request, 'visitors/report_detail.html', {'date':date, 'df': df, 'visitor_number':visitor_num, 'gender':gender, 'age':age, 'time':time})
    return render(request, 'visitors/report.html') 

# Dashboard
def dashboard_with_pivot(request):
    return render(request, 'visitors/dashboard_with_pivot.html', {})

def pivot_data(request):
    dataset = Visitor.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

visitor_analysis/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

visitor_analysis/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

visitor_analysis/visitor_analysis/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p>We like django</p>
</body>
</html>

visitor_analysis/visitor_analysis/templates/base_layout.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visitors</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        {% if user.is_authenticated %}
        <!-- <h1><a href="{% url 'visitors:list' %}">Visitor List</a></h1> -->
        <h1><a href="{% url 'visitors:report' %}">Report</a></h1>
        <h1><a href="{% url 'visitors:dashboard_with_pivot' %}">Dashboard(Flexmonster)</a></h1>
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type = "submit">Logout</button>
                    </form>
                </li>
                <li>
                    <a href="{% url 'visitors:register' %}" class="highlight">Register Visitor</a>
                </li>
            </ul>
        </nav>
        {% else %}
        <nav>
            <ul>
                <li><a href="{% url 'accounts:login'%}">Login</a></li>
                <li><a href="{% url 'accounts:signup'%}">Signup</a></li>
        {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

visitor_analysis/visitor_analysis/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to Visitor Analysis</p>
</body>
</html>

visitor_analysis/visitors/templates/visitors/dashboard_with_pivot.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard with Flexmonster</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
    <style>
/* Charts Style  */

.fm-charts-color-1 {
  fill: #ffa600 !important;
}

.fm-charts-color-2 {
  fill: #7eae26 !important;
}

.fm-charts-color-3 {
  fill: #00a45a !important;
}

.fm-charts-color-4 {
  fill: #df3800 !important;
}

.fm-charts-color-5 {
  fill: #e95800 !important;
}

.fm-charts-color-6 {
  fill: #ffa600 !important;
}</style>
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'visitors:pivot_data' %}"></div>
<div id="pivot-chart-container"></div>
<script>
function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-table-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data),
                    mapping: {
                        "age": {
                            "caption": "Age",
                            "type": "number"
                        },
                        "date": {
                            "caption": "Date",
                        },
                        "user_id": {
                            "caption": "User ID",
                            "type": "number"
                        },
                        "gender": {
                            "caption": "Gender",
                            "type": "string"
                        }
                    }
                },
                // "slice": {
                //     "rows": [{
                //         "uniqueName": "age"
                //     }],
                //     "columns": [{
                //             "uniqueName": "date"
                //         },
                //         {
                //             "uniqueName": "[Measures]"
                //         }

                //     ],
                //     "measures": [{
                //             "uniqueName": "user_id",
                //             "aggregation": "sum"
                //         },
                //         {
                //             "uniqueName": "gender",
                //             "aggregation": "sum"
                //         }
                //     ]
                // }
            }
        });
        // new Flexmonster({
        //     container: "#pivot-chart-container",
        //     componentFolder: "https://cdn.flexmonster.com/",
        //     width: "100%",
        //     height: 430,
        //     //toolbar: true,
        //     report: {
        //         dataSource: {
        //             type: "json",
        //             data: processData(data),
        //             mapping: {
        //                 "product_category": {
        //                     "caption": "Product Category"
        //                 },
        //                 "payment_method": {
        //                     "caption": "Payment Method"
        //                 },
        //                 "shipping_cost": {
        //                     "caption": "Shipping Cost",
        //                     "type": "number"
        //                 },
        //                 "unit_price": {
        //                     "caption": "Unit Price",
        //                     "type": "number"
        //                 }
        //             }
        //         },
        //         "slice": {
        //             "rows": [{
        //                 "uniqueName": "product_category"
        //             }],
        //             "columns": [{
        //                 "uniqueName": "[Measures]"
        //             }],
        //             "measures": [{
        //                 "uniqueName": "Price",
        //                 "formula": "sum(\"shipping_cost\") + sum(\"unit_price\")",
        //                 "caption": "Price"
        //             }]
        //         },
        //         "options": {
        //             "viewType": "charts",
        //             "chart": {
        //                 "type": "pie"
        //             }
        //         }
        //     }
        // });
    }
});


</script>
</body>
</html>

visitor_analysis/visitors/templates/visitors/report.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Report</h1>
    <div class="report">
        <form class="report" action="{% url 'visitors:report' %}" method="post">
            {% csrf_token %}
            <input class="report_form" type="date" id="date" name='date' required>
            <button type="submit">See Report</button>
        </form>
    </li>
     
    </div>
{% endblock %}

visitor_analysis/visitors/templates/visitors/report_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Report Detail : {{date}}</h1>
    <div class="report_detail">
        <h2>Visitor table</h2>
            <div>{{df|safe}}</div>
            <h2>Total number of visitor : {{visitor_number}}</h2>
            <img src = "data:image/png;base64, {{ gender }}" alt="" height="250",width="250">
            <img src = "data:image/png;base64, {{ age }}" alt="" height="250",width="250">
            <img src = "data:image/png;base64, {{ time }}" alt="" height="250",width="250">
    </div>
{% endblock %}

visitor_analysis/visitors/templates/visitors/visitor_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="visitor-detail">
    <div class="visitor">
        <!-- <img src={{visitor.thumb.url}}/> -->
        <p>Id:{{visitor.id}}</p>
        <p>Age:{{visitor.age}}</p>
        <p>Gender:{{visitor.gender}}</p>
        <p>Date:{{visitor.date}}</p>
    </div>
</div>

{% endblock%}

visitor_analysis/visitors/templates/visitors/visitor_register.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="register-visitor">
    <h2>Register Visitor</h2>
    <form class="site-form" action="{% url 'visitors:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Register">
    </form>
</div>

{% endblock %}

visitor_analysis/visitors/templates/visitors/visitors.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Visitor List</h1>
    <div class="visitors">
        {% for visitor in visitors %}
        <div class="visitor">
            <p><a href="/visitors/{{visitor.id}}">Id:{{visitor.id}}</a></p>
            <p>Age:{{visitor.age}}</p>
            <p>Gender:{{visitor.gender}}</p>
            <p>Date:{{visitor.date}}</p>
            <p class="user">registered by {{ visitor.user.username }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}